# please preserve in alphanumeric order
from .cablenoticias import CableNoticiasExtractor
from .canal13 import Canal13Extractor
from .canalcapital import CanalCapitalExtractor
from .canalcaracol import CanalCaracolExtractor
from .canaltro import CanalTROExtractor
from .naciontv import NacionTVExtractor
from .ntn24 import NTN24Extractor
from .senalcolombia import SenalColombiaExtractor
from .senalinstitucional import SenalInstitucionalExtractor
from .staticextractor import StaticExtractor
from .teleamiga import TeleAmigaExtractor
from .teleantioquia import TeleAntioquiaExtractor
from .telecafe import TeleCafeExtractor
from .telecaribe import TeleCaribeExtractor
from .teleislas import TeleIslasExtractor
from .telemedellin import TeleMedellinExtractor
from .telepacifico import TelePacificoExtractor
from .tvcincomonteria import TVCincoMonteriaExtractor
from .zoomcanal import ZoomCanalExtractor
